/* ============================================================================
   Migration Firebird 2.5 - camera-web
   Data: 2026-06-30

   Base usada como referência:
   - TBINSPECAO já existe e fica reservada ao SICFAR.
   - TBPRODUTO já existe e é a tabela atual de produtos.
   - TBOP, TBLINHA_PRODUCAO, TBUSUARIO e TBACESSO já existem.

   Objetivo:
   - Criar TBINSPECAO_MANUAL para os registros deste projeto.
   - Criar TBUSUARIO_FACEID para armazenar somente o descriptor facial.
   - Não criar campo ou tabela para foto do Face ID.

   Observação:
   - Execute com backup prévio da base.
   - O script verifica os metadados antes de criar cada objeto.
   - Se uma tabela já existir com estrutura diferente da esperada, revisar
     manualmente antes de executar em produção.
   ============================================================================ */

SET TERM ^ ;

/* ============================================================================
   1. Tabelas
   ============================================================================ */

EXECUTE BLOCK
AS
BEGIN
    IF (NOT EXISTS(
        SELECT 1
        FROM RDB$RELATIONS
        WHERE RDB$RELATION_NAME = 'TBINSPECAO_MANUAL'
    )) THEN
    BEGIN
        EXECUTE STATEMENT
            'CREATE TABLE TBINSPECAO_MANUAL (' ||
            'INSPECAOMANUAL_ID INTEGER NOT NULL, ' ||
            'STATUS VARCHAR(10), ' ||
            'OP_ID INTEGER, ' ||
            'OP VARCHAR(10), ' ||
            'ERP_PRODUTO VARCHAR(10), ' ||
            'PRODUTO VARCHAR(80), ' ||
            'LOTE VARCHAR(10), ' ||
            'VALIDADE DATE, ' ||
            'GTIN VARCHAR(20), ' ||
            'REGISTRO_ANVISA VARCHAR(20), ' ||
            'LINHAPRODUCAO_ID INTEGER, ' ||
            'FASE VARCHAR(10), ' ||
            'DATA TIMESTAMP DEFAULT CURRENT_TIMESTAMP, ' ||
            'CAMINHO_FOTO VARCHAR(500), ' ||
            'GTIN_CONFORME VARCHAR(3), ' ||
            'DATAMATRIX_CONFORME VARCHAR(3), ' ||
            'LOTE_CONFORME VARCHAR(3), ' ||
            'VALIDADE_CONFORME VARCHAR(3), ' ||
            'OBSERVACOES VARCHAR(1000), ' ||
            'USUARIO_ID INTEGER, ' ||
            'USUARIO VARCHAR(30), ' ||
            'LOCALIZACAO VARCHAR(200), ' ||
            'DATA_INC TIMESTAMP, ' ||
            'USUARIO_I INTEGER, ' ||
            'USUARIONOME_I VARCHAR(30), ' ||
            'DATA_ALT TIMESTAMP, ' ||
            'USUARIO_A INTEGER, ' ||
            'USUARIONOME_A VARCHAR(30), ' ||
            'DATA_DEL TIMESTAMP, ' ||
            'USUARIO_D INTEGER, ' ||
            'USUARIONOME_D VARCHAR(30), ' ||
            'DELETADO CHAR(1) DEFAULT ''N'')';
    END
END
^

EXECUTE BLOCK
AS
BEGIN
    IF (NOT EXISTS(
        SELECT 1
        FROM RDB$RELATIONS
        WHERE RDB$RELATION_NAME = 'TBUSUARIO_FACEID'
    )) THEN
    BEGIN
        EXECUTE STATEMENT
            'CREATE TABLE TBUSUARIO_FACEID (' ||
            'FACEID_ID INTEGER NOT NULL, ' ||
            'USUARIO_ID INTEGER, ' ||
            'DESCRIPTOR_FACIAL BLOB SUB_TYPE BINARY SEGMENT SIZE 512 NOT NULL, ' ||
            'MATRICULA VARCHAR(30), ' ||
            'ATIVO CHAR(1) DEFAULT ''S'', ' ||
            'DATA_INC TIMESTAMP DEFAULT CURRENT_TIMESTAMP, ' ||
            'USUARIO_I INTEGER, ' ||
            'USUARIONOME_I VARCHAR(30), ' ||
            'DATA_ALT TIMESTAMP, ' ||
            'USUARIO_A INTEGER, ' ||
            'USUARIONOME_A VARCHAR(30), ' ||
            'DATA_DEL TIMESTAMP, ' ||
            'USUARIO_D INTEGER, ' ||
            'USUARIONOME_D VARCHAR(30))';
    END
END
^

/* ============================================================================
   2. Constraints
   ============================================================================ */

EXECUTE BLOCK
AS
BEGIN
    IF (NOT EXISTS(
        SELECT 1
        FROM RDB$RELATION_CONSTRAINTS
        WHERE RDB$CONSTRAINT_NAME = 'PK_TBINSPECAO_MANUAL'
    )) THEN
        EXECUTE STATEMENT
            'ALTER TABLE TBINSPECAO_MANUAL ' ||
            'ADD CONSTRAINT PK_TBINSPECAO_MANUAL ' ||
            'PRIMARY KEY (INSPECAOMANUAL_ID)';

    IF (NOT EXISTS(
        SELECT 1
        FROM RDB$RELATION_CONSTRAINTS
        WHERE RDB$CONSTRAINT_NAME = 'FK_TBINSPMANUAL_OP'
    )) THEN
        EXECUTE STATEMENT
            'ALTER TABLE TBINSPECAO_MANUAL ' ||
            'ADD CONSTRAINT FK_TBINSPMANUAL_OP ' ||
            'FOREIGN KEY (OP_ID) REFERENCES TBOP (OP_ID)';

    IF (NOT EXISTS(
        SELECT 1
        FROM RDB$RELATION_CONSTRAINTS
        WHERE RDB$CONSTRAINT_NAME = 'FK_TBINSPMANUAL_LINHA'
    )) THEN
        EXECUTE STATEMENT
            'ALTER TABLE TBINSPECAO_MANUAL ' ||
            'ADD CONSTRAINT FK_TBINSPMANUAL_LINHA ' ||
            'FOREIGN KEY (LINHAPRODUCAO_ID) ' ||
            'REFERENCES TBLINHA_PRODUCAO (LINHAPRODUCAO_ID)';

    IF (NOT EXISTS(
        SELECT 1
        FROM RDB$RELATION_CONSTRAINTS
        WHERE RDB$CONSTRAINT_NAME = 'FK_TBINSPMANUAL_USUARIO'
    )) THEN
        EXECUTE STATEMENT
            'ALTER TABLE TBINSPECAO_MANUAL ' ||
            'ADD CONSTRAINT FK_TBINSPMANUAL_USUARIO ' ||
            'FOREIGN KEY (USUARIO_ID) REFERENCES TBUSUARIO (USUARIO_ID)';

    IF (NOT EXISTS(
        SELECT 1
        FROM RDB$RELATION_CONSTRAINTS
        WHERE RDB$CONSTRAINT_NAME = 'CK_TBINSPMANUAL_GTIN_CONF'
    )) THEN
        EXECUTE STATEMENT
            'ALTER TABLE TBINSPECAO_MANUAL ' ||
            'ADD CONSTRAINT CK_TBINSPMANUAL_GTIN_CONF ' ||
            'CHECK (GTIN_CONFORME IN (''Sim'', ''Não'') ' ||
            'OR GTIN_CONFORME IS NULL)';

    IF (NOT EXISTS(
        SELECT 1
        FROM RDB$RELATION_CONSTRAINTS
        WHERE RDB$CONSTRAINT_NAME = 'CK_TBINSPMANUAL_DATAMAT_CONF'
    )) THEN
        EXECUTE STATEMENT
            'ALTER TABLE TBINSPECAO_MANUAL ' ||
            'ADD CONSTRAINT CK_TBINSPMANUAL_DATAMAT_CONF ' ||
            'CHECK (DATAMATRIX_CONFORME IN (''Sim'', ''Não'') ' ||
            'OR DATAMATRIX_CONFORME IS NULL)';

    IF (NOT EXISTS(
        SELECT 1
        FROM RDB$RELATION_CONSTRAINTS
        WHERE RDB$CONSTRAINT_NAME = 'CK_TBINSPMANUAL_LOTE_CONF'
    )) THEN
        EXECUTE STATEMENT
            'ALTER TABLE TBINSPECAO_MANUAL ' ||
            'ADD CONSTRAINT CK_TBINSPMANUAL_LOTE_CONF ' ||
            'CHECK (LOTE_CONFORME IN (''Sim'', ''Não'') ' ||
            'OR LOTE_CONFORME IS NULL)';

    IF (NOT EXISTS(
        SELECT 1
        FROM RDB$RELATION_CONSTRAINTS
        WHERE RDB$CONSTRAINT_NAME = 'CK_TBINSPMANUAL_VALID_CONF'
    )) THEN
        EXECUTE STATEMENT
            'ALTER TABLE TBINSPECAO_MANUAL ' ||
            'ADD CONSTRAINT CK_TBINSPMANUAL_VALID_CONF ' ||
            'CHECK (VALIDADE_CONFORME IN (''Sim'', ''Não'') ' ||
            'OR VALIDADE_CONFORME IS NULL)';
END
^

EXECUTE BLOCK
AS
BEGIN
    IF (NOT EXISTS(
        SELECT 1
        FROM RDB$RELATION_CONSTRAINTS
        WHERE RDB$CONSTRAINT_NAME = 'PK_TBUSUARIO_FACEID'
    )) THEN
        EXECUTE STATEMENT
            'ALTER TABLE TBUSUARIO_FACEID ' ||
            'ADD CONSTRAINT PK_TBUSUARIO_FACEID ' ||
            'PRIMARY KEY (FACEID_ID)';

    IF (NOT EXISTS(
        SELECT 1
        FROM RDB$RELATION_CONSTRAINTS
        WHERE RDB$CONSTRAINT_NAME = 'FK_TBUSUARIO_FACEID'
    )) THEN
        EXECUTE STATEMENT
            'ALTER TABLE TBUSUARIO_FACEID ' ||
            'ADD CONSTRAINT FK_TBUSUARIO_FACEID ' ||
            'FOREIGN KEY (USUARIO_ID) REFERENCES TBUSUARIO (USUARIO_ID)';

    IF (NOT EXISTS(
        SELECT 1
        FROM RDB$RELATION_CONSTRAINTS
        WHERE RDB$CONSTRAINT_NAME = 'CK_TBUSUARIO_FACEID_ATIVO'
    )) THEN
        EXECUTE STATEMENT
            'ALTER TABLE TBUSUARIO_FACEID ' ||
            'ADD CONSTRAINT CK_TBUSUARIO_FACEID_ATIVO ' ||
            'CHECK (ATIVO IN (''S'', ''N''))';
END
^

/* ============================================================================
   3. Generators
   ============================================================================ */

EXECUTE BLOCK
AS
BEGIN
    IF (NOT EXISTS(
        SELECT 1
        FROM RDB$GENERATORS
        WHERE RDB$GENERATOR_NAME = 'GEN_TBINSPECAOMANUAL_ID'
    )) THEN
    BEGIN
        EXECUTE STATEMENT 'CREATE GENERATOR GEN_TBINSPECAOMANUAL_ID';
        EXECUTE STATEMENT 'SET GENERATOR GEN_TBINSPECAOMANUAL_ID TO 0';
    END

    IF (NOT EXISTS(
        SELECT 1
        FROM RDB$GENERATORS
        WHERE RDB$GENERATOR_NAME = 'GEN_TBUSUARIO_FACEID_ID'
    )) THEN
    BEGIN
        EXECUTE STATEMENT 'CREATE GENERATOR GEN_TBUSUARIO_FACEID_ID';
        EXECUTE STATEMENT 'SET GENERATOR GEN_TBUSUARIO_FACEID_ID TO 0';
    END
END
^

/* ============================================================================
   4. Triggers
   ============================================================================ */

CREATE OR ALTER TRIGGER TRG_TBINSPECAO_MANUAL_BI FOR TBINSPECAO_MANUAL
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.INSPECAOMANUAL_ID IS NULL) THEN
        NEW.INSPECAOMANUAL_ID = GEN_ID(GEN_TBINSPECAOMANUAL_ID, 1);

    IF (NEW.DATA IS NULL) THEN
        NEW.DATA = CURRENT_TIMESTAMP;

    IF (NEW.DATA_INC IS NULL) THEN
        NEW.DATA_INC = CURRENT_TIMESTAMP;

    IF (NEW.DELETADO IS NULL) THEN
        NEW.DELETADO = 'N';
END
^

CREATE OR ALTER TRIGGER TRG_TBINSPECAO_MANUAL_BU FOR TBINSPECAO_MANUAL
ACTIVE BEFORE UPDATE POSITION 0
AS
BEGIN
    IF (NEW.DATA_ALT IS NULL OR NEW.DATA_ALT = OLD.DATA_ALT) THEN
        NEW.DATA_ALT = CURRENT_TIMESTAMP;
END
^

CREATE OR ALTER TRIGGER TRG_TBUSUARIO_FACEID_BI FOR TBUSUARIO_FACEID
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.FACEID_ID IS NULL) THEN
        NEW.FACEID_ID = GEN_ID(GEN_TBUSUARIO_FACEID_ID, 1);

    IF (NEW.DATA_INC IS NULL) THEN
        NEW.DATA_INC = CURRENT_TIMESTAMP;

    IF (NEW.ATIVO IS NULL) THEN
        NEW.ATIVO = 'S';
END
^

CREATE OR ALTER TRIGGER TRG_TBUSUARIO_FACEID_BU FOR TBUSUARIO_FACEID
ACTIVE BEFORE UPDATE POSITION 0
AS
BEGIN
    IF (NEW.DATA_ALT IS NULL OR NEW.DATA_ALT = OLD.DATA_ALT) THEN
        NEW.DATA_ALT = CURRENT_TIMESTAMP;
END
^

/* ============================================================================
   5. Índices
   ============================================================================ */

EXECUTE BLOCK
AS
BEGIN
    IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_TBINSPMANUAL_OP')) THEN
        EXECUTE STATEMENT 'CREATE INDEX IDX_TBINSPMANUAL_OP ON TBINSPECAO_MANUAL (OP)';

    IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_TBINSPMANUAL_OP_ID')) THEN
        EXECUTE STATEMENT 'CREATE INDEX IDX_TBINSPMANUAL_OP_ID ON TBINSPECAO_MANUAL (OP_ID)';

    IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_TBINSPMANUAL_DATA')) THEN
        EXECUTE STATEMENT 'CREATE DESCENDING INDEX IDX_TBINSPMANUAL_DATA ON TBINSPECAO_MANUAL (DATA)';

    IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_TBINSPMANUAL_USUARIO')) THEN
        EXECUTE STATEMENT 'CREATE INDEX IDX_TBINSPMANUAL_USUARIO ON TBINSPECAO_MANUAL (USUARIO)';

    IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_TBINSPMANUAL_USUARIO_ID')) THEN
        EXECUTE STATEMENT 'CREATE INDEX IDX_TBINSPMANUAL_USUARIO_ID ON TBINSPECAO_MANUAL (USUARIO_ID)';

    IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_TBINSPMANUAL_LINHA')) THEN
        EXECUTE STATEMENT 'CREATE INDEX IDX_TBINSPMANUAL_LINHA ON TBINSPECAO_MANUAL (LINHAPRODUCAO_ID)';

    IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_TBINSPMANUAL_FASE')) THEN
        EXECUTE STATEMENT 'CREATE INDEX IDX_TBINSPMANUAL_FASE ON TBINSPECAO_MANUAL (FASE)';

    IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_TBINSPMANUAL_STATUS')) THEN
        EXECUTE STATEMENT 'CREATE INDEX IDX_TBINSPMANUAL_STATUS ON TBINSPECAO_MANUAL (STATUS)';

    IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_TBINSPMANUAL_DATA_INC')) THEN
        EXECUTE STATEMENT 'CREATE DESCENDING INDEX IDX_TBINSPMANUAL_DATA_INC ON TBINSPECAO_MANUAL (DATA_INC)';

    IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_TBINSPMANUAL_DATA_DEL')) THEN
        EXECUTE STATEMENT 'CREATE INDEX IDX_TBINSPMANUAL_DATA_DEL ON TBINSPECAO_MANUAL (DATA_DEL)';

    IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_TBINSPMANUAL_DELETADO')) THEN
        EXECUTE STATEMENT 'CREATE INDEX IDX_TBINSPMANUAL_DELETADO ON TBINSPECAO_MANUAL (DELETADO)';

    IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_TBINSPMANUAL_ERP_PROD')) THEN
        EXECUTE STATEMENT 'CREATE INDEX IDX_TBINSPMANUAL_ERP_PROD ON TBINSPECAO_MANUAL (ERP_PRODUTO)';

    IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_TBINSPMANUAL_LOTE')) THEN
        EXECUTE STATEMENT 'CREATE INDEX IDX_TBINSPMANUAL_LOTE ON TBINSPECAO_MANUAL (LOTE)';

    IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_FACEID_USUARIO_ID')) THEN
        EXECUTE STATEMENT 'CREATE INDEX IDX_FACEID_USUARIO_ID ON TBUSUARIO_FACEID (USUARIO_ID)';

    IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_FACEID_MATRICULA')) THEN
        EXECUTE STATEMENT 'CREATE INDEX IDX_FACEID_MATRICULA ON TBUSUARIO_FACEID (MATRICULA)';

    IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_FACEID_ATIVO')) THEN
        EXECUTE STATEMENT 'CREATE INDEX IDX_FACEID_ATIVO ON TBUSUARIO_FACEID (ATIVO)';

    IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_FACEID_USUARIO_ATIVO')) THEN
        EXECUTE STATEMENT 'CREATE INDEX IDX_FACEID_USUARIO_ATIVO ON TBUSUARIO_FACEID (USUARIO_ID, ATIVO)';

    IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_FACEID_DATA_INC')) THEN
        EXECUTE STATEMENT 'CREATE DESCENDING INDEX IDX_FACEID_DATA_INC ON TBUSUARIO_FACEID (DATA_INC)';

    IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_FACEID_DATA_DEL')) THEN
        EXECUTE STATEMENT 'CREATE INDEX IDX_FACEID_DATA_DEL ON TBUSUARIO_FACEID (DATA_DEL)';
END
^

SET TERM ; ^

COMMIT;

/* ============================================================================
   6. Validação pós-migration
   ============================================================================ */

SELECT
    RDB$RELATION_NAME
FROM RDB$RELATIONS
WHERE RDB$RELATION_NAME IN ('TBINSPECAO_MANUAL', 'TBUSUARIO_FACEID')
ORDER BY RDB$RELATION_NAME;

SELECT
    RDB$GENERATOR_NAME
FROM RDB$GENERATORS
WHERE RDB$GENERATOR_NAME IN ('GEN_TBINSPECAOMANUAL_ID', 'GEN_TBUSUARIO_FACEID_ID')
ORDER BY RDB$GENERATOR_NAME;

SELECT
    RDB$TRIGGER_NAME
FROM RDB$TRIGGERS
WHERE RDB$TRIGGER_NAME IN (
    'TRG_TBINSPECAO_MANUAL_BI',
    'TRG_TBINSPECAO_MANUAL_BU',
    'TRG_TBUSUARIO_FACEID_BI',
    'TRG_TBUSUARIO_FACEID_BU'
)
ORDER BY RDB$TRIGGER_NAME;
